// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSearch() {
  return window['go']['main']['App']['CancelSearch']();
}

export function ListFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2, arg3);
}

export function RemoveDropboxIgnored(arg1) {
  return window['go']['main']['App']['RemoveDropboxIgnored'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetDropboxIgnored(arg1) {
  return window['go']['main']['App']['SetDropboxIgnored'](arg1);
}
