// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSearch():Promise<void>;

export function ListFiles(arg1:string,arg2:string,arg3:boolean):Promise<Array<any>>;

export function RemoveDropboxIgnored(arg1:Array<string>):Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SetDropboxIgnored(arg1:Array<string>):Promise<Array<string>>;
